version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    AWS_REGION: "ap-northeast-1"
phases:
  install:
    runtime-versions: 
        docker: 18
  pre_build:
      commands:
        - bash codebuild/pre_build.sh
  build:
      commands:
        - echo "touching sam-layer-packaged.yaml and chmod to 777 for samcli user to write in. See http://bit.ly/2Qd5Pxy"
        - touch sam-layer-packaged.yaml && chmod 777 sam-layer-packaged.yaml
        - make publish-new-version-to-sar
  post_build:
      commands:
        - BUILT_VERSION=$(cat VERSION) 
        - aws --region ap-northeast-1 sns publish --topic-arn $SNS_TOPIC_ARN --message "[OK] aws-lambda-layer-eksctl version ${BUILT_VERSION} published to SAR us-east-1"
