version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "cn-north-1"
    AWS_REGION: "cn-north-1"
    DOCKER_MIRROR: "hub-mirror.c.163.com/"
    S3BUCKET: "pahud-tmp-cn-north-1"   

phases:
  install:
    runtime-versions: 
        docker: 18
  pre_build:
      commands:
        - bash codebuild/pre_build.sh
  build:
      commands:
        - echo "touching sam-layer-packaged.yaml and chmod to 777 for samcli user to write in. See http://bit.ly/2Qd5Pxy"
        - touch sam-layer-packaged.yaml && chmod 777 sam-layer-packaged.yaml
        - S3BUCKET=$(S3BUCKET) DOCKER_MIRROR=$(DOCKER_MIRROR) make publish-new-version-to-sar-cn
  post_build:
      commands:
        - BUILT_VERSION=$(cat VERSION) 
        - aws --region ${AWS_REGION} sns publish --topic-arn $SNS_TOPIC_ARN --message "[OK] aws-lambda-layer-eksctl version ${BUILT_VERSION} published to SAR ${AWS_REGION}"
